default: &default
  adapter: postgresql
  encoding: unicode
  database: peluqueria
  pool: 5
  username: postgres
  password: eseadri92
  host: localhost

development: 
  <<: *default

production:
  adapter: postgresql
  host: <%= ENV["DB_HOST"] %>
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>